// platform/modules/manifest.mjs - the module catalogue.
//
// Modules are the capabilities an ecosystem can run. A theme switches a default
// set of them on (see platform/themes), but every module is always present in
// the codebase. The flags describe intent, they do not gate code.
//
// The contract fields align to docs/PLATFORM_CORE_CONTRACT.md. They are
// documentation-as-data for now, but they make the reusable module boundary
// explicit before code is extracted from the Bak'd On The Bay proof ecosystem.

export const MODULES = [
  {
    key: 'ticketing',
    label: 'Ticketing',
    summary: 'Approval-gated package purchase; Eventbrite link unlocked after review.',
    purpose: 'Give qualified people and organizations access to paid experiences, packages, and marketplace entry points.',
    entities: ['person', 'organization', 'ecosystem', 'experience', 'marketplace'],
    dataOwned: ['ticket_orders', 'ticket_providers'],
    dataRead: ['applications', 'events'],
    permissions: ['admin manages providers', 'approved participant unlocks access'],
    configuration: ['provider', 'package rules', 'approval requirements', 'purchase links'],
    events: ['ticket.access_requested', 'ticket.order_synced', 'ticket.package_unlocked'],
    trustControls: ['approval gate', 'payment-provider disclosure', 'audit trail'],
    aiUse: 'May summarize purchase readiness only after consent and approval context are available.',
    productOverrides: ['package names', 'pricing', 'Eventbrite links', 'event copy'],
    functions: ['applications'],
    pages: ['package-access.html'],
  },
  {
    key: 'applications',
    label: 'Applications',
    summary: 'Configurable intake and review workflows for ecosystem participation.',
    purpose: 'Let people and organizations ask to participate, then help operators review and approve them fairly.',
    entities: ['person', 'organization', 'ecosystem', 'opportunity'],
    dataOwned: ['applications'],
    dataRead: ['profiles', 'accounts', 'crm_people', 'crm_companies'],
    permissions: ['public submits', 'admin reviews'],
    configuration: ['roles', 'questions', 'contracts', 'status workflow', 'approval email copy'],
    events: ['application.submitted', 'application.approved', 'application.rejected'],
    trustControls: ['status visibility', 'internal notes boundary', 'audit trail'],
    aiUse: 'May help categorize or summarize applications only with operator disclosure and human review.',
    productOverrides: ['vendor copy', 'sponsor tiers', 'speaker formats', 'DJ/entertainment labels'],
    functions: ['applications'],
    pages: ['vendor-application.html', 'sponsor-application.html', 'speaker-application.html', 'dj-application.html'],
  },
  {
    key: 'crm',
    label: 'CRM',
    summary: 'Deduplicated people and companies with roles, notes, pipeline, and relationship context.',
    purpose: 'Turn participation into durable relationships across people, companies, ecosystems, and opportunities.',
    entities: ['person', 'organization', 'relationship', 'opportunity'],
    dataOwned: ['crm_people', 'crm_companies', 'crm_person_roles', 'crm_company_events'],
    dataRead: ['applications', 'profiles', 'events'],
    permissions: ['admin manages CRM', 'future organization representatives manage their own records'],
    configuration: ['pipeline stages', 'roles', 'tags', 'follow-up rules'],
    events: ['crm.person_linked', 'crm.company_linked', 'crm.followup_created'],
    trustControls: ['operator-only notes', 'data export path', 'correction path'],
    aiUse: 'May recommend follow-ups or introductions only with consent-compatible relationship data.',
    productOverrides: ['sales labels', 'sponsor/vendor pipeline stages'],
    functions: ['crm'],
    pages: [],
  },
  {
    key: 'advertising',
    label: 'Advertising',
    summary: 'Campaigns, creatives, delivery log and advertiser billing.',
    purpose: 'Create transparent paid visibility for businesses without hiding incentives or distorting trust.',
    entities: ['organization', 'marketplace', 'analytics', 'opportunity'],
    dataOwned: ['ad_campaigns', 'ad_creatives', 'ad_events'],
    dataRead: ['crm_companies', 'events'],
    permissions: ['admin manages campaigns', 'future advertiser manages own campaigns'],
    configuration: ['placements', 'creative rules', 'billing rules', 'disclosure labels'],
    events: ['ad.impression', 'ad.click', 'ad.campaign_created'],
    trustControls: ['sponsored disclosure', 'frequency controls', 'reporting guardrails'],
    aiUse: 'May optimize placement only against outcome and guardrail metrics, not addictive engagement.',
    productOverrides: ['sponsor packages', 'placement names', 'rate card'],
    functions: ['ads', 'dashboards'],
    pages: [],
  },
  {
    key: 'community',
    label: 'Community',
    summary: 'Feed, reels, stories and member hub.',
    purpose: 'Help ecosystem members share useful context, find collaborators, and build healthy community momentum.',
    entities: ['person', 'community', 'conversation', 'knowledge'],
    dataOwned: ['social_posts', 'social_comments', 'social_likes', 'social_follows', 'social_media'],
    dataRead: ['profiles', 'accounts', 'events'],
    permissions: ['member creates content', 'owner/admin moderates'],
    configuration: ['post types', 'visibility defaults', 'media limits', 'moderation rules'],
    events: ['community.post_created', 'community.comment_created', 'community.followed'],
    trustControls: ['delete controls', 'reporting roadmap', 'visibility controls', 'media ownership'],
    aiUse: 'May summarize public community activity only with clear source context and user controls.',
    productOverrides: ['prompt copy', 'event timing', 'community categories'],
    functions: ['social'],
    pages: ['feed.html', 'reels.html', 'stories.html', 'hub.html'],
  },
  {
    key: 'messaging',
    label: 'Messaging',
    summary: 'Direct messages and group chats.',
    purpose: 'Turn discovery into consent-based conversations and follow-up.',
    entities: ['person', 'conversation', 'relationship', 'opportunity'],
    dataOwned: ['social_messages', 'social_groups', 'social_group_members', 'social_group_messages'],
    dataRead: ['profiles', 'accounts'],
    permissions: ['member sends messages', 'group owner manages membership'],
    configuration: ['group defaults', 'message media rules', 'notification preferences'],
    events: ['message.sent', 'group.created', 'group.member_added'],
    trustControls: ['participant boundary', 'mute preferences', 'delete/report roadmap'],
    aiUse: 'Private messages are excluded from AI use unless every participant explicitly opts in.',
    productOverrides: ['default groups', 'event-specific group copy'],
    functions: ['messages', 'groups'],
    pages: ['messages.html', 'groups.html'],
  },
  {
    key: 'directory',
    label: 'Directory',
    summary: 'Self-authored public profiles, searchable.',
    purpose: 'Make the right people and organizations discoverable inside an ecosystem.',
    entities: ['person', 'organization', 'relationship', 'opportunity'],
    dataOwned: ['profiles'],
    dataRead: ['accounts', 'crm_people', 'crm_companies'],
    permissions: ['member edits own profile', 'admin approves visibility'],
    configuration: ['profile fields', 'roles', 'visibility defaults', 'featured rules'],
    events: ['profile.created', 'profile.approved', 'profile.viewed'],
    trustControls: ['profile approval', 'visibility controls', 'correction path'],
    aiUse: 'May use public profile fields for recommendations when personalization is enabled.',
    productOverrides: ['role labels', 'directory filters', 'profile prompts'],
    functions: ['profiles'],
    pages: ['directory.html', 'profile-view.html'],
  },
  {
    key: 'floorplan',
    label: 'Floor Plan',
    summary: 'Interactive, to-scale draft and published floor plan.',
    purpose: 'Help people navigate physical spaces and find place-based opportunities.',
    entities: ['experience', 'organization', 'opportunity', 'marketplace'],
    dataOwned: ['floorplan'],
    dataRead: ['events', 'profiles', 'crm_companies'],
    permissions: ['admin edits layout', 'public views published map'],
    configuration: ['venue dimensions', 'booth rules', 'published state', 'map labels'],
    events: ['floorplan.saved', 'floorplan.published', 'booth.viewed'],
    trustControls: ['draft/publish boundary', 'location clarity', 'operational review'],
    aiUse: 'May suggest navigation or booth discovery only from published floor-plan data.',
    productOverrides: ['venue layout', 'booth labels', 'Bayfront-specific assets'],
    functions: ['floorplan'],
    pages: ['floorplan.html', 'floorplan-editor.html'],
  },
  {
    key: 'cms',
    label: 'CMS',
    summary: 'Per-page site content, theme and section order, edited in the admin.',
    purpose: 'Let each ecosystem configure public content without source edits.',
    entities: ['ecosystem', 'knowledge', 'experience'],
    dataOwned: ['site_settings', 'site_media'],
    dataRead: ['events'],
    permissions: ['admin edits site content'],
    configuration: ['page keys', 'section order', 'theme overrides', 'media assets'],
    events: ['cms.settings_saved', 'cms.media_uploaded', 'cms.media_deleted'],
    trustControls: ['audit trail', 'media ownership', 'rollback roadmap'],
    aiUse: 'May help draft public copy only when an operator explicitly requests it.',
    productOverrides: ['homepage copy', 'event page sections', 'brand imagery'],
    functions: ['site-settings', 'site-media'],
    pages: ['admin-homepage.html'],
  },
  {
    key: 'scheduling',
    label: 'Scheduling',
    summary: 'Education schedule and future appointments, sessions, office hours, and programs.',
    purpose: 'Create time-based opportunities for learning, mentoring, and coordinated participation.',
    entities: ['experience', 'person', 'organization', 'opportunity'],
    dataOwned: ['events.settings.schedule'],
    dataRead: ['profiles', 'applications'],
    permissions: ['admin manages schedule', 'public views schedule'],
    configuration: ['session types', 'speakers', 'timeslots', 'venues'],
    events: ['schedule.session_created', 'schedule.session_viewed'],
    trustControls: ['speaker approval', 'time/place accuracy', 'change visibility'],
    aiUse: 'May recommend sessions when profile interests and personalization consent allow it.',
    productOverrides: ['speaker lineup', 'session copy', 'event hours'],
    functions: ['events', 'site-settings'],
    pages: ['education-schedule.html'],
  },
  {
    key: 'ai',
    label: 'AI',
    summary: 'Assistive generation, analysis, recommendations, introductions, and opportunity discovery.',
    purpose: 'Help people discover opportunities they would not have found alone.',
    entities: ['person', 'organization', 'opportunity', 'relationship', 'knowledge', 'analytics'],
    dataOwned: ['future_ai_recommendations', 'future_ai_explanations'],
    dataRead: ['profiles', 'crm_people', 'crm_companies', 'events', 'applications'],
    permissions: ['user controls personalization', 'admin configures ecosystem AI policy'],
    configuration: ['personalization defaults', 'explanation templates', 'consent requirements', 'guardrail metrics'],
    events: ['ai.recommendation_shown', 'ai.recommendation_accepted', 'ai.recommendation_hidden'],
    trustControls: ['launch gate', 'explainability', 'consent', 'reset personalization', 'human escalation'],
    aiUse: 'This module governs AI use and must follow docs/TRUST_DATA_AI_FOUNDATION.md.',
    productOverrides: ['product-specific prompts after trust review'],
    functions: [],
    pages: [],
  },
]
